name: Bump version, commit and push tag
on:
  workflow_call:
jobs:
  bump_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
      # Setup node
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Install dependencies
      - run: npm install
      # Get the current version from package.json
      - name: Get the current version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      # Print the current version
      - run: echo "The current version is ${{ steps.package-version.outputs.current-version }}"
      # Bump version and provide new version as output
      - name: Bump version (Dry run)
        id: version-bump-dry-run
        if: ${{ success() }}
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          DRY_RUN: true
          INITIAL_VERSION: ${{ steps.package-version.outputs.current-version }}
      # Update package.json with the new version
      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main
        with:
          version: ${{ steps.version-bump-dry-run.outputs.new_tag }}
      # Create a new Changelog
      - run: npm run changelog
      # Bump version and push tag
      - name: Bump version and push tag
        id: version-bump
        if: ${{ success() }}
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: ${{ steps.package-version.outputs.current-version }}
          DEFAULT_BUMP: patch
      # Commit changes
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: updated package.json and CHANGELOG.md
