name: Bump version, commit and push tag
on:
  pull_request:
    branches:
      - 'feature/*'
  workflow_call:
jobs:
  format_test:
    uses: ./.github/workflows/test_format.yml
  bump_version:
    needs: format_test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [ 20.x ]
    # Only run when the target is main and the format_test job has passed
    if: github.base_ref == 'refs/heads/main' && (github.event.pull_request.action == 'opened' || github.event.pull_request.action == 'reopened')
    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.refs }}
      # Setup node
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Install dependencies
      - run: npm install
      # Get the current version from package.json
      - name: Get the current version from package.json
        if: github.base_ref == 'refs/heads/main' && (github.event.pull_request.action == 'opened' || github.event.pull_request.action == 'reopened')
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      # Print the current version
      - run: echo "The current version is ${{ steps.package-version.outputs.current-version }}"
      # Bump version and push tag
      - name: Bump version and push tag
        id: version-bump
        if: ${{ success() }}
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # DRY_RUN: true
          INITIAL_VERSION: ${{ steps.package-version.outputs.current-version }}
      # Update package.json with the new version
      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main
        with:
          version: ${{ steps.version-bump.outputs.new_tag }}
      # Create a new Changelog
      - run: npm run version
      # Commit changes
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: updated package.json and CHANGELOG.md
