name: CI
on:
  push:
    branches:
      - 'main'
jobs:
  update_version:
    uses: ./.github/workflows/bump_version.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    # Requires the format_test job to pass
    needs: update_version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
        with :
          ref: ${{ github.refs }}
      # Setup node
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # Add the registry URL to publish to NPM (optional)
          registry-url: 'https://registry.npmjs.org'
          # Add the scope of the package to publish to NPM (optional)
          scope: '@rohit1901'
      # Install dependencies
      - name: Install dependencies
        if: ${{ success() }}
        run: npm install
      - name: Build the project
        if: ${{ success() }}
        run: npm run build
      # Publish to NPM
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
