name: CI
on:
  push:
    branches:
      - 'feature/*'
      - 'main'
  pull_request:
    branches: [ main ]
    types: [opened, closed]

jobs:
  format_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v3
      # Build steps
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Node Install
        run: npm install
      - name: Prettify code
        if: ${{ success() }}
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write src/**/*.ts !src/out/**/*
      - name: Test
        if: ${{ success() }}
        run: npm test
      - name: Build (Dry Run)
        if: ${{ success() }}
        run: npm run build-dry-run --if-present
  build:
    needs: format_test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    if: ${{ success() }} && github.event_name == 'push' && ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Node Install
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
        run: npm install
      - name: Bump version and push tag
        uses: RueLaLa/auto-tagger@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_NUMBER: ${{ github.event.number }}
      - name: Build
        run: npm run build
