name: CI
on:
  push:
    branches:
      - 'feature/*'
      - 'main'
jobs:
  format_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v3
      # Build steps
      - name: Node Install, Test and Build
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      - run: npm run build-dry-run --if-present
      - name: Prettify code
        if: ${{ success() }}
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write src/**/*.ts !src/out/**/*
