# This is a basic workflow to help you get started with Actions

name: Lint

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x, 20.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run prettify
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Applying formatting changes
          branch: ${{ github.short_ref }}
